# Generated by Django 4.2.1 on 2025-10-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200, verbose_name='Název události')),
                ('band', models.CharField(max_length=200, verbose_name='kapela')),
                ('start_of_event', models.DateTimeField(verbose_name='datum akce')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=200, verbose_name='název projektu')),
                ('description', models.TextField(verbose_name='popis')),
            ],
        ),
    ]
