# Generated by Django 4.2.25 on 2025-10-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_rename_events_event_rename_projects_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Událost', 'verbose_name_plural': 'Události'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekty'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_title',
            new_name='title',
        ),
    ]
