# Generated by Django 4.2.25 on 2025-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_event_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulek')),
                ('photo', models.ImageField(upload_to='', verbose_name='foto')),
            ],
        ),
    ]
