# Generated by Django 4.2.25 on 2025-10-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakty',
            },
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Fotka', 'verbose_name_plural': 'Fotky'},
        ),
    ]
