# Generated by Django 4.2.25 on 2025-10-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_contact_alter_photos_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
