# Generated by Django 4.2.25 on 2025-10-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0008_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telephone',
        ),
    ]
