# Generated by Django 4.2.25 on 2025-10-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0009_remove_contact_email_remove_contact_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='def', max_length=200, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.CharField(default='123456789', max_length=100),
        ),
    ]
