# Generated by Django 4.2.25 on 2025-10-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0011_alter_contact_email_alter_contact_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telephone',
        ),
    ]
