# Generated by Django 4.2.25 on 2025-10-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0012_remove_contact_email_remove_contact_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'O mě',
                'verbose_name_plural': 'O mě',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default='none', max_length=200, verbose_name='odkaz'),
            preserve_default=False,
        ),
    ]
