# Generated by Django 4.2.25 on 2025-10-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0013_aboutme_event_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='odkaz')),
                ('title', models.CharField(max_length=200, verbose_name='popisek')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videa',
            },
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Koncert', 'verbose_name_plural': 'Koncerty'},
        ),
    ]
