# Generated by Django 4.2.25 on 2025-10-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0014_video_rename_photos_photo_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(verbose_name='odkaz'),
        ),
    ]
