# Generated by Django 4.2.25 on 2025-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0015_alter_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=200, verbose_name='odkaz'),
        ),
    ]
