# Generated by Django 4.2.25 on 2025-10-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0016_alter_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='normalized_title',
            field=models.CharField(default='title_example', max_length=200),
            preserve_default=False,
        ),
    ]
