# Generated by Django 4.2.25 on 2025-10-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0017_video_normalized_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
