# Generated by Django 4.2.25 on 2025-10-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0018_video_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='foto',
            field=models.ImageField(default='none', upload_to='', verbose_name='foto'),
            preserve_default=False,
        ),
    ]
