# Generated by Django 4.2.25 on 2025-10-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0019_project_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='foto',
            new_name='photo',
        ),
    ]
